### ISSUE TITLE
Login against the database

### ISSUE THREAD

**Issue by t-jones** [Warthog710/church-library#10]
- Hash password, store, compare

**Comment by t-jones** [comment]
hey @Warthog710, this should be a secure hash, that is a one-way hash.  A one-way hash takes a string of bytes (the password in this case) and converts it into a random chunk of data which is then hex or base-64 encoded.  If you have the hash, there is no way to recover the original password if it is a good password (unless you are the NSA).  When a user is created, hash their password, store the hash, and throw away the plain text.  On subsequent logins, hash the password they enter and compare it to the stored hash.  If they match, the password is correct.

Examples of secure hashes are MD5 (although this one is compromised so don't use it), SHA1 or SHA-512.  There are other SHA variants; any will work for out purposes.  There should be some php library which will do this.

**Comment by Warthog710** [comment]
@t-jones 
Okay, I understand. I will make the changes when I find the time. In the meantime, I will research secure password hashing with PHP.
