### ISSUE TITLE
Update Checked-Out Resources Page to Only Show Checked-Out Books 

### ISSUE THREAD

**Issue by frenchy-mark** [Warthog710/church-library#14]
-Current page exists, confirm SQL query correct
-Confirm legible display

**Comment by frenchy-mark** [comment]
@t-jones @Warthog710 can this issue be closed now?  What is our issue review process?

**Comment by Warthog710** [comment]
@frenchy-mark  
Not sure, I thought it was the responsibility of the person who fixed the issue to close the issue. Although, I am probably wrong.

Also, just looked at your new SQL query and it is returning a 0 result set. It doesn't seem to work on my end. Your DB is probably set up different than mine somehow.

**Comment by frenchy-mark** [comment]
@Warthog710, I'll look into this tonight.  You have my DB structure from the create statements in the DB guide, as well as the DB backup I provided.  First troubleshooting steps:
* Ensure the result set shouldn't be zero (by looking at the raw transaction_log table)
* Ensure the transaction_log type field values match the query (1 = check in, 2 = check out).

**Comment by frenchy-mark** [comment]
Testing query in MySQL Workbench:
![checked_out_results](https://user-images.githubusercontent.com/42653965/45195706-c12beb00-b20d-11e8-9546-95fc30fd529a.PNG)

Testing query in the app:
![checked_out_results_in_app](https://user-images.githubusercontent.com/42653965/45195745-f3d5e380-b20d-11e8-8957-51144f5257f4.PNG)

I noticed the db name changed when you set it up on your system, did you make other changes to the DB (specifically transaction_log table)?  If you email me a DB backup I could restore it on my system and do some tests.  As it is right now, everything I'm looking at is working.

Just an FYI moving forward - providing additional information is always helpful and gets team members past "it doesn't work."  "It doesn't work" and "work's locally" are the he-said/she-said of the dev world and don't move the issue closer to resolution.

**Comment by Warthog710** [comment]
@frenchy-mark 
Thanks for the info. I will put that into practice into the future. As to changes that I personally made to the DB. Other than changing the name of the actual DB I don't believe anything else changed that would affect the SQL query. 

Also, if you look at the Master branch of the project you will see a .sql file in there. This is a backup of the DB that I have been keeping updated for this use. 

I will play around with it on my end as well seeing if I can solve the issue. 

Here is a pic of my current transaction log table.
![transaction_log](https://user-images.githubusercontent.com/40554666/45198473-9ba5de00-b21b-11e8-813a-7b437efe700f.PNG)

**Comment by frenchy-mark** [comment]
Thank you @Warthog710 !  That screenshot did show me an error in the query.  Stand by for a fix...
